prometheus-exporter:
    run-as-user: root
    path: /usr/local/bin/
    launch-command: ./srl-prometheus-exporter
    search-command: ./srl-prometheus-exporter
    version-command: /usr/local/bin/srl-prometheus-exporter -v
    wait-for-config: Yes
    start-order: 100
    config-delivery-format: proto-json # json, proto-json, binary-tlvs
    failure-threshold: 10
    failure-action: 'wait=60'
    yang-modules:
        names:
            - "prometheus-exporter"
        source-directories:
            - "/opt/prometheus-exporter/yang/"
            - "/opt/srlinux/models/iana"
            - "/opt/srlinux/models/ietf"
            - "/opt/srlinux/models/srl_nokia/models"
