project_name: srl-prometheus-exporter
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}-{{.ShortCommit}}
    goos:
      - linux
    goarch:
      - amd64
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: srl-prometheus-exporter
    file_name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    vendor: Nokia
    homepage: https://github.com/karimra/srl-prometheus-exporter
    maintainer: Karim Radhouani <karim.radhouani@nokia.com>
    description: A Prometheus exporter for Nokia SR Linux
    formats:
      - rpm
    license: "BSD 2"
    bindir: /usr/local/bin/
    contents:
      - src: ./yang/prometheus-exporter.yang
        dst: /opt/prometheus-exporter/yang/prometheus-exporter.yang
      - src: ./yml/prometheus-exporter.yml
        dst: /etc/opt/srlinux/appmgr/prometheus-exporter.yml
      - src: ./metrics.yaml
        dst: /usr/local/bin/metrics.yaml
    overrides:
      rpm:
        scripts:
