global:
  scrape_interval:     10s 
  evaluation_interval: 10s 

scrape_configs:
  - job_name: 'srl-exporter'
    scrape_interval: 10s
    consul_sd_configs:
      - server: clab-prom-exporter-consul-agent:8500
        services:
          - srl-prometheus-exporter