---
name: release
on:
  push:
    tags:
      - v*

env:
  GOVER: 1.21.3
  GORELEASER_VER: v1.22.1

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOVER }}
      - run: go test -cover ./...
        env:
          CGO_ENABLED: 0

  release:
    runs-on: ubuntu-22.04
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOVER }}
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://karimra:${TOKEN}@github.com".insteadOf "https://github.com"
      - name: Release with goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: ${{ env.GORELEASER_VER }}
          args: release --clean -f .goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
